In [4]:
import numpy as np

In [6]:
c = np.array([[1,2,0],[4,6,5],[7,8,9]])

In [8]:
d = np.ravel(c) #return same array
e = c.flatten() 

In [10]:
d

array([1, 2, 0, 4, 6, 5, 7, 8, 9])

In [12]:
e

array([1, 2, 0, 4, 6, 5, 7, 8, 9])

In [14]:
e[0]=33


In [18]:
e

array([33,  2,  0,  4,  6,  5,  7,  8,  9])

In [20]:
c

array([[1, 2, 0],
       [4, 6, 5],
       [7, 8, 9]])

In [22]:
d[0] =44

In [24]:
d

array([44,  2,  0,  4,  6,  5,  7,  8,  9])

In [26]:
c

array([[44,  2,  0],
       [ 4,  6,  5],
       [ 7,  8,  9]])

In [30]:
import numpy as np
Array = np.array([2,4,6,8])
print(Array)
Array[2]=33
print(Array)

[2 4 6 8]
[ 2  4 33  8]


In [44]:
Array.min()

2

In [46]:
Array.max()

33

In [48]:
Array.mean()

11.75

In [63]:
Array.reshape(2,2)

array([[ 2,  4],
       [33,  8]])

In [71]:
Flatter = Array.flatten()
print(Flatter)

[ 2  4 33  8]


In [73]:
two = np.array([[6,4],[8,2]])
two


array([[6, 4],
       [8, 2]])

In [87]:
Ver =np.vstack(two)
print(Ver)

[[6 4]
 [8 2]]


In [89]:
Hori = np.hstack(two)
print(Hori)

[6 4 8 2]


In [93]:
Oned = np.array([3,3,3,2,4,5,8,6,9])
Oned.shape


(9,)

In [95]:
Oned.reshape(3,3)

array([[3, 3, 3],
       [2, 4, 5],
       [8, 6, 9]])

In [111]:
Rev = Oned[::-1]
print("Orginal : ",Oned)
Rev

Orginal :  [3 3 3 2 4 5 8 6 9]


array([9, 6, 8, 5, 4, 2, 3, 3, 3])